### PR TITLE
Some convenience utilities

### PR DESCRIPTION
**Pull request by nsmith-**

### CODE REVIEW

**Comment by nsmith-** [comment]
@pieterdavid would appreciate if you can review https://github.com/cms-nanoAOD/correctionlib/tree/convenience#installation instructions. Also, do you have an RDataFrame example? Should we add some sort of `correctionlib.register()` function to teach ROOT RDataFrame the bindings?

**Comment by pieterdavid** [comment]
@nsmith- that looks good to me!
I have examples for RDF from python and C++ (very similar, but maybe also interesting for the CMakeLists.txt - the `config --cmake` option is very nice, but I think some people may want a bit more detail in the description), see [here](https://gist.github.com/pieterdavid/a560e65658386d70a1720cb5afe4d3e9).
`correctionlib.register` (probably convenient to have indeed) based on what I'm currently using would be something like this:
```python
def register():
    import os.path
    import pkg_resources
    from cppyy import gbl  # PyROOT without pythonization
    gbl.gSystem.Load(pkg_resources.resource_filename("correctionlib", os.path.join("lib", "libcorrectionlib.so")))
    gbl.gInterpreter.AddIncludePath(pkg_resources.resource_filename("correctionlib", "include"))
    gbl.gROOT.ProcessLine('#include "correction.h"')
```
where the last two could become a little bit simpler:
```python
    hdr = pkg_resources.resource_filename("correctionlib", os.path.join("include", "correction.h")))
    gbl.gROOT.ProcessLine('#include "{}"'.format(hdr))
```
if we'd remove the version header include from `correction.h` (with ROOT it's a runtime dependency, unfortunately), but there's nothing else in the include directory, so fine either way.
Let me know if I should turn (some of) this into a PR.

**Comment by nsmith-** [comment]
I've added a `correctionlib.register_pyroot_binding` function, perhaps I can then link to your gist in the README for a detailed example of using RDataFrame?

**Comment by pieterdavid** [comment]
> I've added a `correctionlib.register_pyroot_binding` function, perhaps I can then link to your gist in the README for a detailed example of using RDataFrame?

Fine with me, I updated the python one to use the `correctionlib.register_pyroot_binding` function.
For loading the shared library in a more cross-platform way: I think if first adding the directory with `gSystem.AddDynamicPath`, `gSystem.Load("libcorrectionlib")` should work for both mac and linux (works on linux, I have no easy way to test on other platforms), but then windows probably still needs a special case without "lib", so not such a big difference.

**Comment by nsmith-** [comment]
Thanks for the input. If you later want to migrate the example to this repo (e.g. in sphinx docs) feel free to make a PR, but the gist should already provide a good start for people.

**Pull request merged**
