### PR TITLE
Migrate to pydantic2

### PR DESCRIPTION
**Pull request by nsmith-**
Trying first to just bump the version.

### CODE REVIEW

**Comment by nsmith-** [comment]
This will close #218 and resolve https://github.com/cms-nanoAOD/correctionlib/pull/195#issuecomment-1920662596

**Comment by GaetanLepage** [comment]
Thanks @nsmith- !

**Comment by GaetanLepage** [comment]
Will there be a release of `correctionlib` soon ?
It could help us to update some packages (such as `coffea`) on [nixpkgs](https://github.com/NixOS/nixpkgs).

**Comment by nsmith-** [comment]
Yes, once #219 is merged I'll make a minor version.

**Comment by GaetanLepage** [comment]
> Yes, once #219 is merged I'll make a minor version.

Ok great !

**Pull request merged**
