### PR TITLE
Simple encoder to make JSON files more compact

### PR DESCRIPTION
**Pull request by IzaakWN**
This is a simple, standalone JSON encoder class that can be used to make the JSON code compact, but still readable. It has by default an indent (two spaces), but
1. It keeps lists of primitives (integers, floats or strings) on one single line.
    ```
    [ 1, 2, 3, 4 ]
    ```
    instead of 
    ```
    [
        1,
        2,
        3,
        4
    ]
     ```
2. Short dictionaries with primitive values are kept one single line as well,
    ```
    { "key": "nom", "value": 1.0 }
    ```
    instead of 
    ```
    {
      "key": "nom",
      "value": 1.0
    }
     ```
3. Long lists of primitives is split evenly if it exceeds the user-set `maxlistlen` (default `25`):
      ```
     [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
        14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26
     ]
      ```

A simple help function with several optional arguments is provided:
```
from correctionlib import JSONEncoder
JSONEncoder.write(corr,"example.json")
```

Some examples of JSON output are in https://github.com/IzaakWN/correctionlib/tree/TauPOG_v2/data/tau

### CODE REVIEW

**Comment by nsmith-** [comment]
Not sure if you saw, but I made a PR to your PR to fix the linting issues https://github.com/IzaakWN/correctionlib/pull/3

**Comment by IzaakWN** [comment]
> Not sure if you saw, but I made a PR to your PR to fix the linting issues [IzaakWN#3](https://github.com/IzaakWN/correctionlib/pull/3)

Ah no, I did not, let me check.

**Comment by IzaakWN** [comment]
Somehow I did not get the notification. Let me resolve the conflicts, because I added a bunch of new things (like splitting lists of long strings).

**Review by nsmith- — APPROVED** [review]
Looks good, thanks for this. I was always a bit worried the "human-readability" was disappearing with the default encoders, so this is a nice way to recover it somewhat. I think  that we'll want the cvmfs repo side things to remain compact, possibly gzipped, but this could be used to expand those into something nicer to read for inspection and debugging.

**Pull request merged**
