### PR TITLE
Link against libz and pthread privately

### LINKED ISSUE #235: The exported CMake configuration doesn't look for dependencies correctly
The following `CMakeLists.txt` fails to generate in LCG 104 (correctionlib 2.2.2, but as far as I can tell the code hasn't changed since), with a trivial `test.cc`:
```cmake
cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
project(test)
find_package(correctionlib)
add_executable(test test.cc)
target_link_libraries(test correctionlib)
```
I get the following output:
```
$ cmake -B build $(correction config --cmake)
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos7/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /cvmfs/sft.cern.ch/lcg/releases/gcc/12.1.0-57c96/x86_64-centos7/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.8s)
CMake Error at /cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-centos7-gcc12-opt/cmake/correctionlib-targets.cmake:59 (set_target_properties):
  The link interface of target "correctionlib" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /cvmfs/sft.cern.ch/lcg/views/LCG_104/x86_64-centos7-gcc12-opt/cmake/correctionlibConfig.cmake:10 (include)
  CMakeLists.txt:3 (find_package)


-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
The reason is that ZLIB (and Threads) are added as `PUBLIC` dependencies here (not specifying anything equates to `PUBLIC`): https://github.com/cms-nanoAOD/correctionlib/blob/5b75bf5c42e24aea38b994e385e61e8735a08a93/CMakeLists.txt#L52-L55

This informs CMake that any dependent target needs to add link `libz` and `libpthread` explicitly. This is wrong: neither `zlib.h` nor threads are part of the public interface of correctionlib. These should be made `PRIVATE` instead:
```cmake

if(ZLIB_FOUND)
  target_link_libraries(correctionlib PRIVATE ZLIB::ZLIB)
endif()
if(Threads_FOUND AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  target_link_libraries(correctionlib PRIVATE Threads::Threads)
endif()
```
Note that linking the dependent targets against `libz.so` or `libpthreads.so` is not needed, the linker is smart enough to figure out this part.

Alternatively, [Config.cmake.in](https://github.com/cms-nanoAOD/correctionlib/blob/master/Config.cmake.in) should use [find_dependency](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html#command:find_dependency) to find zlib and pthreads at import time.

### PR DESCRIPTION
**Pull request by nsmith-**
Fixes #235

Tested by creating `CMakeLists.txt`:
```cmake
cmake_minimum_required(VERSION 3.16 FATAL_ERROR)
project(test)
find_package(correctionlib)
add_executable(test test.cc)
target_link_libraries(test correctionlib)
```
and `test.cc`:
```cpp
#include "correction.h"

using correction::CorrectionSet;

int main(int argc, char** argv) {
  auto cset = CorrectionSet::from_file("electron.json");
  auto corr = cset->at("corr");
}
```
and confirming `cmake $(correction config --cmake) . && make` completed successfully. Without this patch, I get the error
```
CMake Error at /Users/ncsmith/src/correctionlib/.env/lib/python3.12/site-packages/correctionlib/cmake/correctionlib-targets.cmake:60 (set_target_properties):
  The link interface of target "correctionlib" contains:

    ZLIB::ZLIB

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /Users/ncsmith/src/correctionlib/.env/lib/python3.12/site-packages/correctionlib/cmake/correctionlibConfig.cmake:10 (include)
  CMakeLists.txt:3 (find_package)
```

### CODE REVIEW

**Comment by nsmith-** [comment]
@lmoureaux sorry this fell off my radar. Take a look

**Comment by lmoureaux** [comment]
No worries, we're all very busy :) This is the error I was reporting and one of the proposed solutions, so I'm happy!

I'm wondering if this could be used as a basic test of the C++ interface. It seems there is currently none?

**Comment by nsmith-** [comment]
There is only a test through the PyROOT binding at the moment:
https://github.com/cms-nanoAOD/correctionlib/blob/87d0a14aaab4d0de422368d47d9a0c31a22669f1/tests/test_binding.py#L32-L36
but yes it would be good to verify the static compilation

**Review by lmoureaux — APPROVED** [review]
Awesome!

**Comment by nsmith-** [comment]
There is some issue with compiling and running this test example that I cannot debug as I don't have a windows machine. Calling it good enough without.

**Pull request merged**
