### PR TITLE
feat: Add Python runtime specification to Binder

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Add a Python 3.10 runtime spec with binder/runtime.txt.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@nsmith- this is ready for review.

**Comment by matthewfeickert** [comment]
@nsmith- I now see that `correctionlib` is listed as only having support up to Python 3.9

https://github.com/cms-nanoAOD/correctionlib/blob/8d9ec74bb6df2457c522104841ee442d3ea410d1/setup.cfg#L21-L26

Is there anything keeping it from using Python 3.10? Or has this just not been updated?

**Comment by nsmith-** [comment]
It builds and runs fine on 3.10, as conformed by the wheel building. I just did not update the setup.cfg

**Comment by matthewfeickert** [comment]
Okay great! I just wanted to make sure I hadn't setup a runtime that would fail. :+1:

**Pull request merged**
